version: 2

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.11"
  jobs:
    create_environment:
      - asdf plugin add pixi
      - asdf install pixi latest
      - asdf global pixi latest
    install:
      - pixi install --environment=docs
    build:
      html:
        - pixi run --environment=docs sphinx-build -T -b html docs $READTHEDOCS_OUTPUT/html
