name: liquid-ref
channels:
  - mantid/label/main
  - conda-forge
  - defaults
dependencies:
  - mantid=6.10
  - matplotlib
  - numpy
  - lmfit
  - versioningit
  - pre-commit
  - pytest
  - pytest-cov
  - codecov
  - conda-build
  - python-build
  - versioningit
  - boa
  - conda-verify
  - sphinx
  - sphinx-rtd-theme
