name: lr_reduction
channels:
  - mantid-ornl
  - mantid
  - conda-forge
dependencies:
  - lmfit
  - mantid>=6.12.0.2
  - matplotlib
  # development dependencies
  - boa
  - codecov
  - conda-build
  - conda-verify
  - pre-commit
  - pytest
  - pytest-cov
  - python-build
  - ruff
  - sphinx
  - sphinx-rtd-theme
  - versioningit
  - myst-parser
