name: liquid-ref
channels:
  - mantid/label/main
  - conda-forge
  - defaults
dependencies:
  - lmfit
  - mantid=6.10
  - matplotlib
# development dependencies
  - boa
  - codecov
  - conda-build
  - conda-verify
  - pre-commit
  - pytest
  - pytest-cov
  - python-build
  - versioningit
