name: lr_reduction
channels:
  - mantid/label/main
  - conda-forge
  - defaults
dependencies:
  - lmfit
  - mantid=6.12
  - matplotlib
  # development dependencies
  - boa
  - codecov
  - conda-build
  - conda-verify
  - pre-commit
  - pytest
  - pytest-cov
  - python-build
  - ruff
  # - sphinx
  # - sphinx-rtd-theme
  - versioningit
  - myst-parser
