name: liquid-ref
channels:
  - mantid/label/main
  - conda-forge
  - defaults
dependencies:
  - mantid=6.7.0
  - matplotlib
  - pre-commit
  - pytest
  - pytest-cov
  - numpy
  - lmfit
  - codecov
  - conda-build
  - python-build
  - versioningit
  - boa
  - conda-verify
