name: liquid-ref
channels:
  - conda-forge
  - default
  - mantid
dependencies:
  - python=3.8
  - pre-commit
  - pytest
  - pytest-cov
  - numpy
  - lmfit
  - mantidworkbench>=6.7.0
  - codecov
  - conda-build
  - python-build
  - versioningit
  - boa
  - conda-verify
