site_name: "Liquids Reflectometer"
repo_name: "LiquidsReflectometer"
repo_url: "https://github.com/neutrons/LiquidsReflectometer"

theme:
  name: "readthedocs"
  docs_dir: docs/
  # logo: ""

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [reduction/lr_reduction]
          import:
            - https://docs.python.org/3/objects.inv
            - https://mkdocstrings.github.io/objects.inv
            - https://mkdocstrings.github.io/griffe/objects.inv
          options:
            # See: https://mkdocstrings.github.io/usage/handlers/?h=docstring_style#selection-options
            docstring_style: google
            docstring_options:
              docstring_section_style: table
              ignore_init_summary: yes
            merge_init_into_class: yes
            # separate_signature: yes
            show_signature: no
            show_source: no
            show_root_full_path: no
            show_root_toc_entry: False
            filters:
              - "!^_[^_]"
              # - '^_[^_]'

extra:
  social:
    - icon: "fontawesome/solid/house"
      link: "https://neutrons.ornl.gov"
    - icon: "fontawesome/brands/github-alt"
      link: "https://github.com/neutrons/LiquidsReflectometer"
# copyright: "Copyright &copy; 2020 - 2023 [Glass](glass-ships.com)"
