[project]
name = "LiquidsReflectometer"
description = "Reduction scripts for the Liquids Reflectometer. This includes both automated reduction scripts and useful scripts to reprocess data."
dynamic = ["version"]
requires-python = ">=3.8"
dependencies = [
    "mantidworkbench"
]

[tool.ruff]
line-length = 140
# https://beta.ruff.rs/docs/rules/
select = ["A", "ARG", "E", "W", "F", "PT", "RUF100"]
ignore = ["E402", # module level import not at top of file
          "E722", # bare except
          "E741", "E743", # ambiguous function name, generally 'l'
          "F403", # wild imports
          "F405", "F821", # unknown names from probably from wild imports
]

[tool.black]
line-length = 140

[tool.pytest.ini_options]
pythonpath = [
  ".", "reduction", "scripts", "tests/data/liquidsreflectometer-data/nexus/"
]

testpaths = ["tests", "tests/data/liquidsreflectometer-data"]
norecursedirs = [".git", "tmp*", "_tmp*", "__pycache__", "*dataset*", "*data_set*"]
markers = [
  "datarepo: mark a test as using LiquidsReflectometer-data repository",
  "scripts: mark a test as a script that should be run manually",
]

[build-system]
requires = ["setuptools >= 42", "wheel", "toml", "versioningit"]
build-backend = "setuptools.build_meta"

[tool.versioningit.vcs]
method = "git"
default-tag = "0.0.1"

[tool.versioningit.next-version]
method = "minor"

[tool.versioningit.format]
distance = "{next_version}.dev{distance}"
dirty = "{version}+d{build_date:%Y%m%d}"
distance-dirty = "{next_version}.dev{distance}+d{build_date:%Y%m%d%H%M}"

[tool.versioningit.write]
file = "reduction/_version.py"

[tool.coverage.run]
branch = true

[tool.coverage.report]
skip_empty = true
