[project]
name = "lr_reduction"
description = "Reduction scripts for the Liquids Reflectometer. This includes both automated reduction scripts and useful scripts to reprocess data."
dynamic = ["version", "readme", "license", "dependencies"]
requires-python = ">=3.8"
classifiers = [
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3"
]

[tool.ruff]
line-length = 140
# https://beta.ruff.rs/docs/rules/
select = ["A", "ARG", "E", "W", "F", "I", "PT", "RUF100"]
ignore = ["E402", # module level import not at top of file
          "E722", # bare except
          "E741", "E743", # ambiguous function name, generally 'l'
          "F403", # wild imports
          "F405", "F821", # unknown names from probably from wild imports
]

[tool.coverage.run]
branch = true

[tool.coverage.report]
skip_empty = true

[tool.pytest.ini_options]
pythonpath = [
  ".", "reduction", "scripts", "tests/data/liquidsreflectometer-data/nexus/"
]

testpaths = ["tests"]
norecursedirs = [".git", "tmp*", "_tmp*", "__pycache__", "*dataset*", "*data_set*"]
markers = [
  "datarepo: mark a test as using LiquidsReflectometer-data repository",
  "scripts: mark a test as a script that should be run manually",
]
