name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [next, qa, main]
    tags: ['v*']

jobs:

  tests:
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 100  # Fetch all history for accurate versioning
          fetch-tags: true  # Fetch tags to ensure versioning works correctly

      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@v0.8.10
        with:
          manifest-path: pyproject.toml

      - name: Download test data
        working-directory: ./reduction
        run: |
          git submodule update --init

      - name: Test with pytest
        run: |
          pixi run test-all

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        if: github.actor != 'dependabot[bot]'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Build documentation
        run: |
          pixi run docs-build --environment docs
          test -f ./docs/build/html/index.html

      - name: build conda package
        run: |
          pixi run conda-build
          test -f lr_reduction-*.conda

      - name: upload conda package
        uses: actions/upload-artifact@v4
        with:
          name: conda-package
          path: lr_reduction-*.conda

  verify_conda_package:
    needs: tests
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 100
          fetch-tags: true
          ref: ${{ github.ref }}

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          miniforge-version: latest
          use-mamba: true
          channels: mantid-ornl,conda-forge
          python-version: 3.10

      - name: Download conda package
        uses: actions/download-artifact@v4
        with:
          name: conda-package
          path: /tmp/local-channel/linux-64

      - name: Install the package
        run: |
          mamba install --yes conda-build,conda-verify
          python -m conda_index /tmp/local-channel
          mamba install --yes -c /tmp/local-channel -c mantid-ornl -c conda-forge lr_reduction

      - name: Verify the installation
        run: |
          python -c "import lr_reduction"
          python -c "import mantid"
          python -c "import lmfit"
